### ISSUE TITLE
Add option to disable 'loop' of options

### ISSUE THREAD

**Issue by Alber70g** [ruyadorno/ipt#43]
First off: this tool is awesome! (Would be even more happy if it'd be non-node, but it's fine so far)

Anyhow, right now I'm using the following to select one of the recent branches I've been to:

```bash
git reflog | grep -m 10 checkout | cut -d ' ' -f 6 | ipt | xargs git checkout

? Select an item: (Use arrow keys)
❯ platform
  master
  b4fe806588027a1e07d6287cade7ecd3f4ee7de5
  release-3.25.x
  platform
  release-3.25.x
  develop
```

Even though `platform` is first, it doesn't show as the first once you scroll 3 down and 3 up:

```bash
? Select an item:
  release-3.25.x
  fix/polyfills
  develop
❯ platform
  master
  b4fe806588027a1e07d6287cade7ecd3f4ee7de5
  release-3.25.x
```

The problem is, this output is 'looped': once I go down, there's no way to determine which one is the first. In this case its annoying since I'm using it to see what's the recent branches, but they end up both above and below each other. So either an indicator `---` to separate the start from the end of the list or a flag to disable the 'circle' would be useful.

**Comment by ruyadorno** [comment]
hi @Alber70g that's awesome feedback! thanks for taking the time! So here are a few possible solutions, hopefully one of them can quickly fix your workflow:

- One simple solution if the list is not too large is to use the `-S` option to increase the number of displaying lines in the interface (this way it stops the looping 😉 ) e.g. `ipt -S 15`
- In the case you have a really long list, I think you should consider the `-a` option to use the autocomplete option so that you filter out items instead of manually walking through the list
- Lastly, I don't think an indicator/separator would be a very nice thing to have built-in (maybe we can just use something like `sed` to append it to the list?) but I'll def keep it in mind in the case more people ask for it
